# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import kaetzchen_pb2 as kaetzchen__pb2


class KaetzchenStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OnRequest = channel.unary_unary(
        '/proto.Kaetzchen/OnRequest',
        request_serializer=kaetzchen__pb2.Request.SerializeToString,
        response_deserializer=kaetzchen__pb2.Response.FromString,
        )


class KaetzchenServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OnRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KaetzchenServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OnRequest': grpc.unary_unary_rpc_method_handler(
          servicer.OnRequest,
          request_deserializer=kaetzchen__pb2.Request.FromString,
          response_serializer=kaetzchen__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.Kaetzchen', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
